# Generated by Django 2.1.3 on 2018-11-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('id_externo', models.CharField(max_length=10, unique=True)),
                ('prop1', models.CharField(blank=True, help_text='No se que es todavía (YV o CV)', max_length=10, null=True)),
                ('prop2', models.CharField(blank=True, help_text='No se que es todavía (0 1 o nulo)', max_length=10, null=True)),
            ],
        ),
    ]
