# Generated by Django 2.1.3 on 2018-11-24 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.CharField(blank=True, max_length=180, null=True)),
                ('id_externo', models.CharField(help_text='codigo se llama al traerlo', max_length=40)),
                ('id_externo2', models.CharField(help_text='id se llama al traerlo', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ramal',
            unique_together={('empresa', 'id_externo')},
        ),
    ]
