# Generated by Django 2.1.3 on 2018-11-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('lineas', '0002_auto_20181124_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='origen',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='origen',
            unique_together={('empresa', 'id_externo')},
        ),
    ]
