# Generated by Django 2.1.3 on 2018-11-24 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0003_auto_20181124_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='origen',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lineas.Linea'),
        ),
    ]
