# Generated by Django 2.1.3 on 2018-11-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0006_auto_20181124_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.CharField(blank=True, max_length=180, null=True)),
                ('id_externo', models.CharField(help_text='codigo se llama al traerlo, hay vacios!', max_length=40)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas_destino', to='lineas.Origen')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas_origen', to='lineas.Origen')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parada',
            unique_together={('origen', 'id_externo')},
        ),
    ]
