# Generated by Django 2.1.3 on 2018-11-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0007_auto_20181124_1704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parada',
            unique_together={('origen', 'destino', 'id_externo')},
        ),
    ]
