# Generated by Django 2.1.3 on 2018-11-25 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineas', '0008_auto_20181124_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esperando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesEspera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.CharField(blank=True, max_length=180, null=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esperas_como_destino', to='lineas.Origen')),
                ('espera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='bondis.Esperando')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esperas_como_origen', to='lineas.Origen')),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esperas', to='lineas.Parada')),
            ],
        ),
    ]
