# Generated by Django 2.1.3 on 2018-11-25 18:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bondis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosEspera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Antes de que una opcion cargue lo nuevo desactiva todos los existentes de modo que solo se vea la última llamada')),
                ('salida', models.CharField(blank=True, max_length=300, null=True)),
                ('llegada', models.CharField(blank=True, max_length=300, null=True)),
                ('info', models.CharField(blank=True, max_length=300, null=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('opcion_espera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='bondis.OpcionesEspera')),
            ],
        ),
    ]
