# Generated by Django 2.1.3 on 2018-11-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondis', '0003_auto_20181125_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosespera',
            name='falta_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
